### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by AllegroBarry** [codeagent/treemap#5]
Hello, I'm attempting to install codeagent\treemap according to your instructions, and I'm seeing the following:

Senshu:barry babola$ php composer.phar require codeagent\treemap

                                                                                                                       
  [InvalidArgumentException]                                                                                           
  Could not find a matching version of package codeagenttreemap. Check the package spelling, your version constraint   
  and that the package is available in a stability which matches your minimum-stability (stable).                      
                                                                                                                       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

Any idea what I need to do to fix this?

**Comment by codeagent** [comment]
I will fix this up as soon as possible. Thanks for feedback

**Comment by AllegroBarry** [comment]
Hello, I'm sorry I wasted your time on this. I'm guessing you developed this on Windows? I am installing on unix/linux. I got it to work by changing...

require codeagent\treemap

to...

require codeagent/treemap

So I simply changed the backward slash to a forward slash, and it seemed to work. I am able to produce treemaps as documented.

If there is anything you need to fix, it might be your documentation, but your software is fine. Again, sorry about the unintended detour.
